apiVersion: emunet.emunet.io/v1
kind: EmuNet
metadata:
  name: emunet-example
  namespace: default
spec:
  totalReplicas: 20
  selector:
    matchLabels:
      app: emunet-pod
  imageGroups:
    - image: nginx:alpine
      replicas: 18
    - image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/k8s.gcr.io/pause:3.2
      replicas: 2
